name: Daily Holiday Update

on:
  schedule:
    - cron: '* * * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Load .env variables
        run: |
          echo "ACCESS_TOKEN=${{ secrets.HOLIDAY_API_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.PUSH_TOKEN }}" >> $GITHUB_ENV

      - name: Run PHP script
        run: php holiday_commit.php
